### PR TITLE
hotfix for (#329) support for regional language codes

### LINKED ISSUE #329: WhereYouGo not using correct default language
## Bug description

My device is setup to use German language.
When starting WhereYouGo it behaves kind of strange:
- In the beginning the main menu was shown in German and also all strings also in German except that all strings in "Settings" are english.
- When using Settings - Localization - Language and setting it to "German" the whole app uses German strings
- When using Settings - Localization - Language and setting it to "System Default" the whole app is in English from then on

## WhereYouGo version

2021.12.25-NB

## Reproducible

Kind of...at least something is fishy here

## System information
Android 11, Samsung S20

### PR DESCRIPTION
**Pull request by sk-juroot**
Fixes #329 

## Description
Reworked `CustomActivity.setLocale()` to internally handle regional and non-regional language codes on various system versions.

## Related issues
- #329 

## Additional context
This code contains hardcoded check for Portuguese language (as the only regional-coded language in this project right now), since various Android devices may report this language as non-regional, causing falling back to English even when proper language asset is present.

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by Lineflyer** [comment]
@bekuno Can you review the code?

File: src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java [hunk 1]
```diff
@@ -253,14 +253,34 @@ private void unbindDrawables(View view) {
...
+        } else {
+            lang = new Locale(languageCode).toString();
+        }
+
+        // need to parse language codes with dash and hyphen
+        String[] loc = lang.split("[-_]");
+        if (loc.length == 1) {
+            if (loc[0].equals("pt")) {
+                // nasty hotfix for Portuguese language selected without regional code
+                locale = new Locale(loc[0], loc[0]);
```
Comment (bekuno) [inline src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java:273]: Let's do it the way around - rename the language `pt_PT` to `pt`.
I created Issue #342 for it.
After that these lines are not more necessary.

Comment (sk-juroot) [reply src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java:273]: Since I won't mess up your translation workflow and settings, I'll be happy to remove this code when proposed change in #342 is resolved.

File: src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java [hunk 2]
```diff
@@ -253,14 +253,34 @@ private void unbindDrawables(View view) {
...
+        // we need to get language and region first even for default to correctly initialize Locale
         if (languageCode.equals("default")) {
-            lang = Locale.getDefault().getLanguage();
+            lang = Locale.getDefault().toString();
+        } else {
+            lang = new Locale(languageCode).toString();
+        }
+
+        // need to parse language codes with dash and hyphen
+        String[] loc = lang.split("[-_]");
```
Comment (bekuno) [inline src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java:269]: The language divider is `_`, the `-` is not used.

Comment (sk-juroot) [reply src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java:269]: Older android versions may return locale string with dash instead of hyphen, when default system language is requested and that language is regional for upper lang family. I have my emulator for api 21 set to brasilian portuguese and system returns Locale.getDefault like the second line:

```
customOnCreate(), lang: default
setLocale() lang: pt-br
```

Comment (bekuno) [reply src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java:269]: Interesting, that is not so documented. Then it is fine. :-)

File: src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java (hunk 1 above)
Comment (bekuno) [reply src/main/java/menion/android/whereyougo/gui/extension/activity/CustomActivity.java:273]: That is fine.
Lets go this way.

**Review by bekuno — APPROVED** [review]

**Comment by bekuno** [comment]
> @bekuno Can you review the code?

The PR looks codewise fine.
But I did not tested it on a real device.

**Comment by Lineflyer** [comment]
@sk-juroot 
What do you think?
Shall we include this into the upcoming release or better merge after release to have more time for testing in emulator and in our nightlies?

**Comment by sk-juroot** [comment]
> @Lineflyer 
> Shall we include this into the upcoming release or better merge after release to have more time for testing in emulator and in our nightlies?

Guess there will be no harm in postponing this fix (along with required restart) into another release, there will be some time to reconsider settings in Crowdin and fine-tune expected results.

**Comment by Lineflyer** [comment]
As `master` is separated from `release` now (see branch handling in readme) its fine to merge and test this on `master`= in nightlies
